# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "EPPAD"
product_name = "EPPAD"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"  # Direct chip specification


[matrix]
# Input and output pins are mandatory
input_pins = ["P1_28", "P1_29", "P1_30", "P1_31"]
output_pins = ["P0_00", "P0_01", "P0_04", "P0_05", "P0_07", "P0_08", "P0_11", "P0_12"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
#row2col = true

[layout]
rows = 4
cols = 8
layers = 2

matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7)
"""
# layer 0 (default):
# (the number comes from the order of '[[layer]] entries' in the file)
[[layer]]
name = "base_layer" #optional name for the layer
keys = """
Q W E U I O P Escape
A S D H J K L F5
Left Down Right B N M Z X
C V Up MO(1) Space F G T
"""

# layer 1:
[[layer]]
name = "fn_layer" #optional name for the layer
keys = """
Q W E U I O P Escape
A S D H J K L F5
Left Down Right B N M Z X
C V Up T Space F G T
"""

[[input_device.encoder]]
pin_a = "P0_24"
pin_b = "P0_11"

# Whether to use the MCU's internal pull-up resistor, default to false
internal_pullup = false

# Phase is the working mode of the rotary encoders.
# Available mode:
# - default: EC11 compatible, resolution = 1
# - e8h7: resolution = 2, reverse = true
# - resolution: customized resolution, the resolution value and reverse should be specified later
phase = "default"

# The resolution represents how many pulses the encoder generates per detent.
# For examples, if your rotary encoder has 30 detents in total and generates 15 pulses per 360 degree rotation, then the resolution = 30/15 = 2.
# Number of detents and number of pulses can be found in your encoder's datasheet
resolution = 2

# Whether the direction of the rotary encoder is reversed.
reverse = false

[ble]
enabled = true

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = false
# scrolllock.pin = "PA3"
# scrolllock.low_active = false
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = false



[storage]
# Storage feature is enabled by default
# enabled = false
